### ISSUE TITLE
Suggestion for other integration

### ISSUE THREAD

**Issue by abuisman** [chrisvfritz/rails-javascript-integrations#5]
Hi, 

I just saw the description of the 'pure sprockets with jQuery' setup and while I'd recommend something else like React or Vue, etc. for front-end heavy work, I have created a cool (if I say so myself) plugin for exactly the situation where there is no room for anything but jQuery in a project (due to time, skills, necessity, etc).

Self plug:
https://github.com/abuisman/jquery-freud

What it allows you to do is componentize DOM elements by adding a data-attribute like so:

`<div class='greeting-card' data-behaviours='IncreaseCount'></div>`

The behaviour (class), would look like this:

````
class IncreaseCount
  constructor: (@element, options = {}) ->
    @count = @element.data('count') || 0
    $button = $('<button>Add one</button>')
    @element.append($button)
    $button.on('click', @handleButtonClick)

  buttonClick: =>
    @count = @count + 1;
    @element.find('.count').text(@count)
````

This way you can also selectively apply javascript to DOM elements as they come and go in and out of view while also being able to use classes and objects.

This approach has been very useful for a few years now for several projects where a full front-end framework is not a real option or simply overkill for various reasons.

Maybe you'd like to feature it as an alternative or share your thoughts about it here.

**Comment by chrisvfritz** [comment]
Cool project! It's definitely an option I'll be keeping in mind for teams that already have a large jQuery codebase, but would like to start migrating to a component mindset. 

I'm not sure it's well-suited to my goals for this repo though. I'm mainly targeting teams that are starting a new Rails project and know they will be writing so much JavaScript that integration is something they're researching. I only include the jQuery example to provide a simple reference for the difference between Vue and what they may be doing now. For any substantial front-end, I think it's worth learning something like Vue or React - particularly since for Vue, I see most people becoming productive within a day of reading the docs, which is a pretty low barrier to entry.

Either way though, thanks for sharing! I'm glad that resource exists. :smile:

**Comment by abuisman** [comment]
Thanks! Yes, it works quite well for jQuery-heavy projects or projects that don't really need a lot of front-end engineering.

Vue is indeed fairly easy to start with and the docs are very beginner friendly. I will definitely check back with your repo when I decide to use Vue in a new project. Right now I am busy with evaluating Phoenix (Elixir) so I might incorporate Vue there too ;).

Thanks for having a look and sharing your thoughts.
